name: Dispatch test

on:
  workflow_dispatch:
    inputs:
      page:
        description: 'Page of the repository list to check (currently 1-3)'
        required: true
        type: 'number'
        default: 1

jobs:
  test-number:
    runs-on: ubuntu-latest

    steps:
      - name: Download updater config
        run: echo '${{ github.event.inputs.page }}'
