name: Dispatch test

on:
  workflow_dispatch:
    inputs:
      page:
        description: 'Page of the repository list to check (currently 1-4)'
        required: true
        type: choice
        options:
          - 1
          - 2
          - 3
          - 4

jobs:
  test-number:
    runs-on: ubuntu-latest

    steps:
      - name: Test ${{ github.event.inputs.page }}
        run: echo '${{ github.event.inputs.page }}'
