name: Performance testing
on:
  pull_request:

concurrency:
  group: performance-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  performance-testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1']

    name: performance-${{ matrix.php-versions }}

    steps:
      - name: Checkout server before PR
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          submodules: true
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Apply PR
        env:
          PULL_REQUEST_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PULL_REQUEST_BASE_REF: ${{ github.event.pull_request.base.ref }}
          PULL_REQUEST_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}
        run: |
          echo $PULL_REQUEST_HEAD_REF
          echo $PULL_REQUEST_BASE_REF
          echo $PULL_REQUEST_CLONE_URL

      - name: Apply PR old
        run: |
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.event.pull_request.head.repo.clone_url }}
