name: Performance testing
on:
  pull_request:

concurrency:
  group: performance-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  performance-testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1']

    name: performance-${{ matrix.php-versions }}

    steps:
      - name: Checkout server before PR
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          submodules: true
          ref: ${{ github.event.pull_request.base.ref }}
          
      - name: Checkout server before PR 2
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Apply blueprint
        uses: icewind1991/blueprint@v0.1.2
        with:
          blueprint: tests/blueprints/basic.toml
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Apply PR
        env:
          PULL_REQUEST_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PULL_REQUEST_BASE_REF: ${{ github.event.pull_request.base.ref }}
          PULL_REQUEST_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}
        run: |
          echo pr/$PULL_REQUEST_HEAD_REF
          echo pr/$PULL_REQUEST_BASE_REF
          echo pr/$PULL_REQUEST_CLONE_URL

      - name: Apply PR old
        run: |
          echo pr/${{ github.event.pull_request.head.ref }}
          echo pr/${{ github.event.pull_request.base.ref }}
          echo pr/${{ github.event.pull_request.head.repo.clone_url }}

      - name: Apply PR 2
        run: |
          echo 'pr/${{ github.event.pull_request.head.ref }}'
          echo 'pr/${{ github.event.pull_request.base.ref }}'
          echo 'pr/${{ github.event.pull_request.head.repo.clone_url }}'

      - name: Apply PR 3
        run: |
          echo pr/'${{ github.event.pull_request.head.ref }}'
          echo pr/'${{ github.event.pull_request.base.ref }}'
          echo pr/'${{ github.event.pull_request.head.repo.clone_url }}'
